# Generated by Django 5.1.1 on 2024-10-06 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.utils import OperationalError

def add_autor_field(apps, schema_editor):
    Noticia = apps.get_model('noticias', 'Noticia')
    try:
        # Intenta agregar el campo 'autor'
        schema_editor.add_field(
            Noticia,
            models.ForeignKey(
                settings.AUTH_USER_MODEL,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                name='autor'
            )
        )
    except OperationalError:
        # Si la columna ya existe, no hacer nada
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_autor_field),
    ]
