# Generated by Django 4.2.3 on 2024-10-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_autor'),
        ('noticias', '0003_noticia_autor_noticia_publicado_delete_comentario'),
    ]

    operations = [
    ]
