# Generated by Django 4.2.3 on 2024-10-18 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("noticias", "0005_denuncia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="autor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
