# Generated by Django 4.2.3 on 2024-09-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('no_registrado', 'No Registrado'), ('registrado', 'Registrado'), ('admin', 'Administrador')], default='registrado', max_length=20),
        ),
    ]
